name: ROS2 CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs_on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Build and Run tests
        uses: ros-tooling/action-ros-ci@v0.7
        with:
          package-name: xxxxxxxx
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          rosdep-check: true
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/b8436aa16c0bdbc01081b12caa253cbf16e0fb82/index.yaml
